"""Initial migration

Revision ID: c0724fa87954
Revises: 
Create Date: 2026-05-09 22:34:11.143214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0724fa87954'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_slug'), ['slug'], unique=True)

    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_slug'), ['slug'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('message_thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_low_id', sa.Integer(), nullable=False),
    sa.Column('participant_high_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['participant_high_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['participant_low_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_low_id', 'participant_high_id', name='uq_message_thread_pair')
    )
    with op.batch_alter_table('message_thread', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_thread_participant_high_id'), ['participant_high_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_thread_participant_low_id'), ['participant_low_id'], unique=False)

    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(length=120), nullable=True),
    sa.Column('image_alt', sa.String(length=200), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('featured_pin_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_featured_pin_order'), ['featured_pin_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_owner_id'), ['owner_id'], unique=False)

    op.create_table('user_wanted_categories',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'category_id')
    )
    op.create_table('interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sender_id', 'post_id', name='uq_interest_sender_post')
    )
    with op.batch_alter_table('interest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interest_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interest_sender_id'), ['sender_id'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('notif_type', sa.String(length=20), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    op.create_table('thread_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('recipient_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['message_thread.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thread_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thread_message_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_message_thread_id'), ['thread_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thread_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thread_message_thread_id'))
        batch_op.drop_index(batch_op.f('ix_thread_message_sender_id'))

    op.drop_table('thread_message')
    op.drop_table('post_tags')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_post_id'))
        batch_op.drop_index(batch_op.f('ix_notification_actor_id'))

    op.drop_table('notification')
    with op.batch_alter_table('interest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interest_sender_id'))
        batch_op.drop_index(batch_op.f('ix_interest_post_id'))

    op.drop_table('interest')
    op.drop_table('user_wanted_categories')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_owner_id'))
        batch_op.drop_index(batch_op.f('ix_post_featured_pin_order'))

    op.drop_table('post')
    with op.batch_alter_table('message_thread', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_thread_participant_low_id'))
        batch_op.drop_index(batch_op.f('ix_message_thread_participant_high_id'))

    op.drop_table('message_thread')
    op.drop_table('user')
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_slug'))

    op.drop_table('tag')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_slug'))

    op.drop_table('category')
    # ### end Alembic commands ###
